version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: macho-power
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network
    volumes:
      - ./logs/nginx:/var/log/nginx
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge 