version: '3.8'

services:
  web:
    build: .
    container_name: macho-power
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./logs/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge 